Repository SubhojeetDas1107/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#3 Create guessthenumber.py
  guessthenumber.py
Labels: hacktoberfest-accepted

#2 Create Drawing-Car-Using-Python.py
  Drawing-Car-Using-Python.py
Labels: hacktoberfest-accepted

#5 Create heart.java
  heart.java
Labels: hacktoberfest, hacktoberfest-accepted

#7 Create hacktoberfest.py
  hacktoberfest.py
Labels: good first issue, hacktoberfest-accepted

#11 file add
  Flower_detaction.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#10 addednewproject
  pdffilemerger.py
Labels: hacktoberfest, hacktoberfest-accepted

#12 Create Patterns.cpp
  Patterns.cpp
Labels: hacktoberfest-accepted

#14 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest, hacktoberfest-accepted

#16 sumEvenAfterQueries.py
  sumEvenAfterQueries.py
Labels: hacktoberfest-accepted

#21 Added a new frontent project
  Web Development/nft-preview-card-component/design/active-states.jpg
  Web Development/nft-preview-card-component/design/desktop-design.jpg
  Web Development/nft-preview-card-component/design/desktop-preview.jpg
  Web Development/nft-preview-card-component/design/mobile-design.jpg
  Web Development/nft-preview-card-component/images/favicon-32x32.png
  Web Development/nft-preview-card-component/images/icon-clock.svg
  Web Development/nft-preview-card-component/images/icon-ethereum.svg
  Web Development/nft-preview-card-component/images/icon-view.svg
  Web Development/nft-preview-card-component/images/image-avatar.png
  Web Development/nft-preview-card-component/images/image-equilibrium.jpg
  Web Development/nft-preview-card-component/index.css
  Web Development/nft-preview-card-component/index.html
  Web Development/nft-preview-card-component/readme.md
  Web Development/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#20 Create Greedy.cpp
  Greedy.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#27 Added Gym Website Project and Merge Sort Algorithm
  Merge_sort.cpp
  Web Development/Gym_Website/Gym_Website.css
  Web Development/Gym_Website/Gym_Website.html
  Web Development/Gym_Website/bg.png.jpg
  Web Development/Gym_Website/icon.png.png
Labels: hacktoberfest, hacktoberfest-accepted

#30 Tour and travels website
  Web Development/Natours/index.html
  Web Development/Natours/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#38 Butterfly pattern in java file
  ButterFly.java
Labels: hacktoberfest, hacktoberfest-accepted

#40 Create NodeJS fizzbuzz CLI app
  Scripts/fizzbuzz.js
Labels: hacktoberfest, hacktoberfest-accepted

#46 Create BubbleSort.java
  Scripts/BubbleSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#45 added myself
  StopWatch/README.md
  StopWatch/index.css
  StopWatch/index.html
  StopWatch/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#52 Updated README
  README.md
Labels: documentation, hacktoberfest

#49 Android Developers Words App Completed Submission Kotlin
  App Development/android-basics-kotlin-words-app-starter/.github/ISSUE_TEMPLATE
  App Development/android-basics-kotlin-words-app-starter/.gitignore
  App Development/android-basics-kotlin-words-app-starter/CONTRIBUTING.md
  App Development/android-basics-kotlin-words-app-starter/LICENSE
  App Development/android-basics-kotlin-words-app-starter/README.md
  App Development/android-basics-kotlin-words-app-starter/app/build.gradle
  App Development/android-basics-kotlin-words-app-starter/app/proguard-rules.pro
  App Development/android-basics-kotlin-words-app-starter/app/src/main/AndroidManifest.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/ic_launcher-playstore.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/java/com/example/wordsapp/DetailActivity.kt
  App Development/android-basics-kotlin-words-app-starter/app/src/main/java/com/example/wordsapp/LetterAdapter.kt
  App Development/android-basics-kotlin-words-app-starter/app/src/main/java/com/example/wordsapp/MainActivity.kt
  App Development/android-basics-kotlin-words-app-starter/app/src/main/java/com/example/wordsapp/WordAdapter.kt
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/drawable/ic_baseline_view_list_24.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/drawable/ic_baseline_view_module_24.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/drawable/ic_launcher_background.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/drawable/ic_launcher_foreground.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/layout/activity_detail.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/layout/activity_main.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/layout/item_view.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/menu/layout_menu.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-hdpi/ic_launcher.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-mdpi/ic_launcher.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/values-night/themes.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/values/arrays.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/values/colors.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/values/strings.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/values/styles.xml
  App Development/android-basics-kotlin-words-app-starter/app/src/main/res/values/themes.xml
  App Development/android-basics-kotlin-words-app-starter/build.gradle
  App Development/android-basics-kotlin-words-app-starter/code-of-conduct.md
  App Development/android-basics-kotlin-words-app-starter/gradle.properties
  App Development/android-basics-kotlin-words-app-starter/gradle/wrapper/gradle-wrapper.jar
  App Development/android-basics-kotlin-words-app-starter/gradle/wrapper/gradle-wrapper.properties
  App Development/android-basics-kotlin-words-app-starter/gradlew
  App Development/android-basics-kotlin-words-app-starter/gradlew.bat
  App Development/android-basics-kotlin-words-app-starter/settings.gradle
Labels: hacktoberfest, hacktoberfest-accepted

#53 Updated scripts folder.
  Scripts/AddFirst.java
Labels: hacktoberfest, hacktoberfest-accepted

#58 Updated script folder.
  Scripts/factorial.java
Labels: hacktoberfest-accepted

#56 gilhedi using linked list
  Scripts/gilhedi.c
Labels: hacktoberfest-accepted

#63 Create Counting-Sort.c
  Scripts/Counting-Sort.c
Labels: hacktoberfest-accepted

#60 adding of two binary numbers
  Scripts/BinarySum.cpp
Labels: good first issue, hacktoberfest-accepted

#61 Create EvenFibonacci.java
  Scripts/EvenFibonacci.java
Labels: good first issue, hacktoberfest-accepted

#66 Created a TO-DO List
  Web Development/To-Do_website/background.jpg
  Web Development/To-Do_website/index.html
  Web Development/To-Do_website/script.js
  Web Development/To-Do_website/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#73 Created cyclic sort in cpp
  Scripts/Cyclic_Sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#75 add web app
  Web Development/tic-tac-toe/app.js
  Web Development/tic-tac-toe/index.html
  Web Development/tic-tac-toe/style.css
Labels: hacktoberfest

#76 Added Rock-Paper-Scissor-Game in web development
  Web Development/Rock_Paper_Scissor_Game/brain.js
  Web Development/Rock_Paper_Scissor_Game/index.html
  Web Development/Rock_Paper_Scissor_Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted
